module.exports = [
  {
    slug: "tetris",
    name: "Tetris",
    description: "Stack falling tetrominoes to clear lines and rack up the highest score.",
    category: "arcade",
    difficulty: "medium",
    icon: "🟦",
    tags: ["blocks", "classic", "canvas"],
  },
  {
    slug: "snake",
    name: "Snake",
    description: "Guide the snake to eat food and grow — but don't hit the walls or yourself!",
    category: "arcade",
    difficulty: "easy",
    icon: "🐍",
    tags: ["snake", "classic", "canvas"],
  },
  {
    slug: "breakout",
    name: "Breakout",
    description: "Break all the bricks by bouncing the ball with your paddle.",
    category: "arcade",
    difficulty: "medium",
    icon: "🧱",
    tags: ["ball", "classic", "canvas"],
  },
  {
    slug: "2048",
    name: "2048",
    description: "Slide and merge numbered tiles to reach the 2048 tile.",
    category: "puzzle",
    difficulty: "medium",
    icon: "🔢",
    tags: ["numbers", "merge", "tiles"],
  },
  {
    slug: "minesweeper",
    name: "Minesweeper",
    description: "Reveal all safe squares without triggering a mine. Use logic and luck.",
    category: "puzzle",
    difficulty: "hard",
    icon: "💣",
    tags: ["mines", "logic", "classic"],
  },
  {
    slug: "tictactoe",
    name: "Tic-Tac-Toe",
    description: "Outsmart your opponent in the classic 3×3 grid game. Play vs AI.",
    category: "board",
    difficulty: "easy",
    icon: "⭕",
    tags: ["strategy", "classic", "two-player"],
  },
  {
    slug: "memory-match",
    name: "Memory Match",
    description: "Flip cards to find matching pairs. Train your memory and beat the clock.",
    category: "board",
    difficulty: "easy",
    icon: "🃏",
    tags: ["memory", "cards", "pairs"],
  },
  {
    slug: "mancala",
    name: "Mancala",
    description:
      "Sow seeds around the ancient board, capture your opponent's, and collect the most to win.",
    category: "board",
    difficulty: "medium",
    icon: "🪨",
    tags: ["strategy", "classic", "board", "two-player"],
  },
];
