module.exports = [
  {
    slug: "2048",
    name: "2048",
    description: "Slide and merge numbered tiles to reach the 2048 tile.",
    category: "puzzle",
    difficulty: "medium",
    icon: "🔢",
    tags: ["numbers", "merge", "tiles"],
  },
  {
    slug: "blackjack",
    name: "Blackjack",
    description: "Beat the dealer — get as close to 21 as possible without going bust!",
    category: "board",
    difficulty: "medium",
    icon: "🃏",
    tags: ["cards", "casino", "classic"],
  },
  {
    slug: "breakout",
    name: "Breakout",
    description: "Break all the bricks by bouncing the ball with your paddle.",
    category: "arcade",
    difficulty: "medium",
    icon: "🧱",
    tags: ["ball", "classic", "canvas"],
  },
  {
    slug: "color-block",
    name: "Color Block",
    description: "Place colorful block shapes on the grid and clear full rows and columns.",
    category: "puzzle",
    difficulty: "medium",
    icon: "🟦",
    tags: ["blocks", "casual", "puzzle", "placement"],
  },
  {
    slug: "connect-four",
    name: "Connect Four",
    description: "Drop colored discs into a 7×6 grid and connect four in a row to win.",
    category: "board",
    difficulty: "medium",
    icon: "🔴",
    tags: ["strategy", "two-player", "grid"],
  },
  {
    slug: "domino",
    name: "Domino",
    description:
      "Match tiles end-to-end to build the chain — empty your hand or score the most points to win!",
    category: "board",
    difficulty: "medium",
    icon: "🎲",
    tags: ["tiles", "classic", "board", "two-player"],
  },
  {
    slug: "flappy-bird",
    name: "Flappy Bird",
    description: "Tap to flap — guide the bird through the pipes without crashing!",
    category: "arcade",
    difficulty: "easy",
    icon: "🐦",
    tags: ["flying", "tap", "canvas"],
  },
  {
    slug: "mancala",
    name: "Mancala",
    description:
      "Sow seeds around the ancient board, capture your opponent's, and collect the most to win.",
    category: "board",
    difficulty: "medium",
    icon: "🪨",
    tags: ["strategy", "classic", "board", "two-player"],
  },
  {
    slug: "hangman",
    name: "Hangman",
    description: "Guess the hidden word letter by letter before the hangman is complete!",
    category: "word",
    difficulty: "easy",
    icon: "🪢",
    tags: ["word", "guessing", "classic"],
  },
  {
    slug: "memory-match",
    name: "Memory Match",
    description: "Flip cards to find matching pairs. Train your memory and beat the clock.",
    category: "board",
    difficulty: "easy",
    icon: "🃏",
    tags: ["memory", "cards", "pairs"],
  },
  {
    slug: "minesweeper",
    name: "Minesweeper",
    description: "Reveal all safe squares without triggering a mine. Use logic and luck.",
    category: "puzzle",
    difficulty: "hard",
    icon: "💣",
    tags: ["mines", "logic", "classic"],
  },
  {
    slug: "number-merge",
    name: "Number Merge",
    description: "Drop tiles into columns — equal neighbors merge into their sum, chaining combos!",
    category: "puzzle",
    difficulty: "medium",
    icon: "🔢",
    tags: ["numbers", "merge", "falling", "combo"],
  },
  {
    slug: "pong",
    name: "Pong",
    description: "Two paddles, one ball — first to 7 points wins. Play vs AI or a friend!",
    category: "arcade",
    difficulty: "easy",
    icon: "🏓",
    tags: ["ball", "classic", "canvas", "two-player"],
  },
  {
    slug: "reversi",
    name: "Reversi",
    description: "Outflank your opponent's discs to flip them — most discs at the end wins!",
    category: "board",
    difficulty: "medium",
    icon: "⚫",
    tags: ["strategy", "classic", "board", "two-player"],
  },
  {
    slug: "sliding-puzzle",
    name: "Sliding Puzzle",
    description:
      "Slide numbered tiles into order — arrange 1–15 with the empty space in the bottom-right corner to win!",
    category: "puzzle",
    difficulty: "medium",
    icon: "🔲",
    tags: ["tiles", "logic", "classic", "sliding"],
  },
  {
    slug: "snake",
    name: "Snake",
    description: "Guide the snake to eat food and grow — but don't hit the walls or yourself!",
    category: "arcade",
    difficulty: "easy",
    icon: "🐍",
    tags: ["snake", "classic", "canvas"],
  },
  {
    slug: "space-invaders",
    name: "Space Invaders",
    description:
      "Defend Earth from waves of alien invaders — shoot them all before they reach you!",
    category: "arcade",
    difficulty: "hard",
    icon: "👾",
    tags: ["shooter", "classic", "canvas"],
  },
  {
    slug: "sudoku",
    name: "Sudoku",
    description: "Fill the 9×9 grid so every row, column, and 3×3 box contains digits 1–9.",
    category: "puzzle",
    difficulty: "hard",
    icon: "🔢",
    tags: ["numbers", "logic", "classic"],
  },
  {
    slug: "tetris",
    name: "Tetris",
    description: "Stack falling tetrominoes to clear lines and rack up the highest score.",
    category: "arcade",
    difficulty: "medium",
    icon: "🟦",
    tags: ["blocks", "classic", "canvas"],
  },
  {
    slug: "tictactoe",
    name: "Tic-Tac-Toe",
    description: "Outsmart your opponent in the classic 3×3 grid game. Play vs AI.",
    category: "board",
    difficulty: "easy",
    icon: "⭕",
    tags: ["strategy", "classic", "two-player"],
  },
  {
    slug: "whack-a-mole",
    name: "Whack-a-Mole",
    description: "Moles pop up from holes at random — click them before they disappear!",
    category: "arcade",
    difficulty: "easy",
    icon: "🦔",
    tags: ["reflex", "clicking", "casual", "classic"],
  },
];
